---
- name: Install and configure Apache
  hosts: webservers
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes
